### ISSUE TITLE
Kubeconfig loader does not accept expiry timestamps

### ISSUE THREAD

**Issue by kke** [kontena/k8s-client#102]
Ref: https://github.com/kontena/mortar/issues/93

If `~/.kube/config` / `KUBECONFIG` contains timestamps, the loading will raise a `Psych::DisallowedClass` exception.

Example:

```yaml
  user:
    auth-provider:
      config:
        access-token: 
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: 2019-01-29T14:20:36Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

Time/Date/DateTime should probably be whitelisted.
