### ISSUE TITLE
Client expects to see `namespace` on all resources

### ISSUE THREAD

**Issue by jnummelin** [kontena/k8s-client#32]
It doesn't seem to use the contexts namespace from the config. IMO it should take that into account.

**Comment by SpComb** [comment]
There's some haphazard `namespace` support at the `Client` level, but it's not really very well tested. I'm not entirely sure how the `APIClient` should behave in terms of non-namespaced resources / resources with a default namespace.

**Comment by jnummelin** [comment]
Let's say I want to push a plain pod like
```
kind: Pod
apiVersion: v1
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: foobar
    ports:
      - containerPort: 8080
```
With `kubectl` I could kust `apply` it and `kubectl` would respect the config contexts default namespace, or just use the `default` namespace. I'd expect k8s-client to have the same logic.
