### ISSUE TITLE
`nil` vs. `[]` vs. not-set-att-all

### ISSUE THREAD

**Issue by jnummelin** [kontena/k8s-client#51]
https://github.com/kubernetes/kubernetes/issues/70281

So if I send something either as `nil` or as in empty array, k8s API treats it as not set at all and omits the attribute on the resulting object. This causes problems now when k8s-client saves the config in annotation and determines the json patch operations based on that.

Apply following with k8s-client:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      tolerations:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
```

and after that try to apply e.g.:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      tolerations: []
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
```

The json patch operations send would be:
```
[{"op": "replace", "path":"/spec/tolerations", "value":[]}]
```

Kube API borks with:
```
Error from server: jsonpatch replace operation does not apply: doc is missing key: /spec/tolerations
```

That's because the initial sending of "empty" `tolerations` results in the deployment object actually not having tolerations set at all so we cannot replace them either on later patches.

I think there's two ways to "fix" this:
1. "compact" the resource hash before storing it in the las-applied-config annotation. That way whatever was used omits nulls and empty arrays as if they were not given at all
2. Make the json patch part deal with these. If the patch "calculation" sees the old value as nil/empty array it could transform the operation from `replace` to `add`.

I _think_ option 1 might be more future proof and robust.

@jakolehm @kke WDYT?
